#!/usr/bin/env bash

function get_cert() {
    # Get multiline input for cert
    ssl_cert=""

    while IFS= read -r line; do
        ssl_cert+="$line"$'\n'
    done

    ssl_cert="${ssl_cert%$'\n'}"

    echo "$ssl_cert"
}

install() {
    # Install dependencies
    apt-get update; apt-get upgrade -y; apt-get install curl socat git -y

    # Install docker
    sudo curl -fsSL https://get.docker.com | sh

    # Clone the repo on /opt and get there
    repo_name="Marzban-node"
    mkdir -p /var/lib/$repo_name
    mkdir -p /opt/$repo_name
    cd /opt/$repo_name
    git clone https://github.com/Gozargah/$repo_name

    # Write ssl_cert_client into a file
    local cert_file="/var/lib/marzban-node/ssl_client_cert.pem"
    local cert=$1
    echo "$cert" > "$cert_file"
    chmod 644 "$cert_file"

    # Run
    sudo docker compose up -d

}

check_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        if [ "$ID" == "debian" ] || [ "$ID_LIKE" == "debian" ]; then
            echo "The operating system is Debian-based."
            install
        else
            echo "The operating system is not Debian-based."
        fi
    else
        echo "Unable to determine the operating system."
    fi
}

function main() {
    clear
    echo "Enter your ssl_cert_client generated by Marzban panel: Press enter and ctrl+d when cert content is pasted."
    cert=$(get_cert)
    check_os
}

main
