#!/usr/bin/env bash

function get_cert() {
    echo "Enter your cert from Marzban panel and finaly press ctrl+d: "
    
    # Get multiline input for cert
    ssl_cert=""

    while IFS= read -r line; do
        ssl_cert+="$line"$'\n'
    done

    ssl_cert="${ssl_cert%$'\n'}"

    echo "$ssl_cert"
}

install() {
    # Install dependencies
    apt-get update; apt-get upgrade -y; apt-get install curl socat git -y

    # Install docker
    sudo curl -fsSL https://get.docker.com | sh

    # Clone the repo on /opt and get there
    repo_name="Marzban-node"
    mkdir -p /var/lib/marzban-node
    mkdir -p /opt/$repo_name
    cd /opt/
    git clone https://github.com/Gozargah/$repo_name $repo_name
    cd $repo_name

    # Write ssl_cert_client into a file
    local cert_file="/var/lib/marzban-node/ssl_client_cert.pem"
    cert=$(get_cert)
    echo "$cert" > "$cert_file"
    chmod 644 "$cert_file"
    docker_compose="docker-compose.yml"
    # Write docker-compose
    cat <<EOF > "$docker_compose"
services:
  marzban-node:
    # build: .
    image: gozargah/marzban-node:latest
    restart: always
    network_mode: host

    environment:
      SSL_CLIENT_CERT_FILE: "$cert_file"

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
EOF

    # Run
    sudo docker compose up -d

}

check_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        if [ "$ID" == "debian" ] || [ "$ID_LIKE" == "debian" ]; then
            echo "The operating system is Debian-based."
            install
        else
            echo "The operating system is not Debian-based."
        fi
    else
        echo "Unable to determine the operating system."
    fi
}

function main() {
    clear
    echo "Enter your ssl_cert_client generated by Marzban panel: Press enter and ctrl+d when cert content is pasted."
    check_os
}

main
